export default [
  {
    id: 1,
    companyname: "Company 1",
    representative: "AA",
    companyemail: "otho.smitham@example.com",
    companyphonenumber: "+1(850)1234567",
    companyaddress: "City1 street1",
  },
  {
    id: 11,
    companyname: "Company 11",
    representative: "Ab",
    companyemail: "otho.smitham@example.com",
    companyphonenumber: "+1(850)1234567",
    companyaddress: "City11 street11",
  },
  {
    id: 2,
    companyname: "Company 2",
    representative: "cc",
    companyemail: "otho.smitham@example.com",
    companyphonenumber: "+1(850)1234567",
    companyaddress: "City2 street2",
  },
  {
    id: 3,
    companyname: "Company 1",
    representative: "dd",
    companyemail: "otho.smitham@example.com",
    companyphonenumber: "+1(850)1234567",
    companyaddress: "City3 street3",
  },
  {
    id: 4,
    companyname: "Company 4",
    representative: "ff",
    companyemail: "otho.smitham@example.com",
    companyphonenumber: "+1(850)1234567",
    companyaddress: "City4 street4",
  },
  {
    id: 5,
    companyname: "Company 5",
    representative: "gg",
    companyemail: "otho.smitham@example.com",
    companyphonenumber: "+1(850)1234567",
    companyaddress: "City5 street5",
  },
  {
    id: 6,
    companyname: "Company 6",
    representative: "hh",
    companyemail: "otho.smitham@example.com",
    companyphonenumber: "+1(850)1234567",
    companyaddress: "City6 street6",
  },
  {
    id: 7,
    companyname: "Company 7",
    representative: "ii",
    companyemail: "otho.smitham@example.com",
    companyphonenumber: "+1(850)1234567",
    companyaddress: "City7 street7",
  },
  {
    id: 8,
    companyname: "Company 8",
    representative: "jj",
    companyemail: "otho.smitham@example.com",
    companyphonenumber: "+1(850)1234567",
    companyaddress: "City8 street8",
  },
  {
    id: 9,
    companyname: "Company 9",
    representative: "kk",
    companyemail: "otho.smitham@example.com",
    companyphonenumber: "+1(850)1223427",
    companyaddress: "City1 street9",
  },
  {
    id: 10,
    companyname: "Company 10",
    representative: "ll",
    companyemail: "otho.smitham@example.com",
    companyphonenumber: "+1(850)12342367",
    companyaddress: "City10 street 10",
  }
  
];